### PR TITLE
Fix font

### LINKED ISSUE #132: [PE-D] Corrupted UI Text
There seems to be an error in displaying the data as even newly added data seems to output corrupted text.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: joey-chance/ped#3

### PR DESCRIPTION
**Pull request by whoisjunhong**

### CODE REVIEW

**Review by lzf834 — COMMENTED** [review]
very gud very naise

**Comment by joshuayapwj98** [comment]
LGTM! Hope the font is fixed for Mac!

**Review by joshuayapwj98 — COMMENTED** [review]
LGTM!!

**Review by lzf834 — APPROVED** [review]
will merge this in

**Pull request merged**
